on:
  push:
    branches:
      - master
    tags:
      - "v*"
    paths-ignore:
      - "*.md"
      - "*.json"
      - ".gitignore"
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  BINARY_NAME: aws-masquerade
  THIRD_PARTY_LICENSE_OUTPUT: THIRD_PARTY_LICENSES.html

jobs:
  build-linux-x86_64:
    runs-on: ubuntu-24.04
    env:
      TARGET: x86_64-unknown-linux-musl
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          target: ${{ env.TARGET }}
      - run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools
      - run: cargo build --release --target $TARGET
      - run: |
          mkdir -p "${{ env.TMP_DIR }}"
          cp "${{ env.SOURCE_BINARY }}" "${{ env.TMP_DIR }}"
        if: ${{ github.ref_type == 'tag' }}
        env:
          TMP_DIR: tmp/package/${{ env.BINARY_NAME }}_${{ github.ref_name }}_${{ env.TARGET }}
          SOURCE_BINARY: target/${{ env.TARGET }}/release/${{ env.BINARY_NAME }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: ${{ github.ref_type == 'tag' }}
        with:
          name: tmp-${{ env.TARGET }}
          path: tmp
          retention-days: 1

  build-linux-arm64:
    runs-on: ubuntu-22.04-arm
    env:
      TARGET: aarch64-unknown-linux-musl
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          target: ${{ env.TARGET }}
      - run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools
      - run: cargo build --release --target $TARGET
      - run: |
          mkdir -p "${{ env.TMP_DIR }}"
          cp "${{ env.SOURCE_BINARY }}" "${{ env.TMP_DIR }}"
        if: ${{ github.ref_type == 'tag' }}
        env:
          TMP_DIR: tmp/package/${{ env.BINARY_NAME }}_${{ github.ref_name }}_${{ env.TARGET }}
          SOURCE_BINARY: target/${{ env.TARGET }}/release/${{ env.BINARY_NAME }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: ${{ github.ref_type == 'tag' }}
        with:
          name: tmp-${{ env.TARGET }}
          path: tmp
          retention-days: 1


  build-linux-arm:
    runs-on: ubuntu-24.04
    env:
      TARGET: arm-unknown-linux-musleabihf
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            ghcr.io/rust-cross/rust-musl-cross:${{ env.TARGET }} \
            cargo build --release --target ${{ env.TARGET }}
      - run: |
          mkdir -p "${{ env.TMP_DIR }}"
          cp "${{ env.SOURCE_BINARY }}" "${{ env.TMP_DIR }}"
        if: ${{ github.ref_type == 'tag' }}
        env:
          TMP_DIR: tmp/package/${{ env.BINARY_NAME }}_${{ github.ref_name }}_${{ env.TARGET }}
          SOURCE_BINARY: target/${{ env.TARGET }}/release/${{ env.BINARY_NAME }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: ${{ github.ref_type == 'tag' }}
        with:
          name: tmp-${{ env.TARGET }}
          path: tmp
          retention-days: 1

  build-macos:
    runs-on: macos-latest
    env:
      TARGET: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          target: ${{ env.TARGET }}
      - run: cargo build --release --target $TARGET
      - run: |
          mkdir -p "${{ env.TMP_DIR }}"
          cp "${{ env.SOURCE_BINARY }}" "${{ env.TMP_DIR }}"
        if: ${{ github.ref_type == 'tag' }}
        env:
          TMP_DIR: tmp/package/${{ env.BINARY_NAME }}_${{ github.ref_name }}_${{ env.TARGET }}
          SOURCE_BINARY: target/${{ env.TARGET }}/release/${{ env.BINARY_NAME }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: ${{ github.ref_type == 'tag' }}
        with:
          name: tmp-${{ env.TARGET }}
          path: tmp
          retention-days: 1

  build-windows-x86_64:
    runs-on: windows-latest
    env:
      TARGET: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          target: ${{ env.TARGET }}
      - run: cargo build --release --target $env:TARGET
        env:
          RUSTFLAGS: -C target-feature=+crt-static
      - run: |
          mkdir -p "${{ env.TMP_DIR }}"
          cp "${{ env.SOURCE_BINARY }}.exe" "${{ env.TMP_DIR }}"
        if: ${{ github.ref_type == 'tag' }}
        env:
          TMP_DIR: tmp/package/${{ env.BINARY_NAME }}_${{ github.ref_name }}_${{ env.TARGET }}
          SOURCE_BINARY: target/${{ env.TARGET }}/release/${{ env.BINARY_NAME }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: ${{ github.ref_type == 'tag' }}
        with:
          name: tmp-${{ env.TARGET }}
          path: tmp
          retention-days: 1

  third-party-licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      - run: cargo install cargo-about --features="cli"
      - run: cargo about generate about.hbs > ${{ env.THIRD_PARTY_LICENSE_OUTPUT }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: third_party_licenses
          path: ${{ env.THIRD_PARTY_LICENSE_OUTPUT }}
          retention-days: 1

  packaging:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - build-linux-x86_64
      - build-linux-arm64
      - build-linux-arm
      - build-windows-x86_64
      - build-macos
      - third-party-licenses
    if: ${{ github.ref_type == 'tag' }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          pattern: tmp-*
          merge-multiple: true
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: third_party_licenses
      - run: find . -type f | sort
      - run: ls package | xargs -I {} sh -c 'chmod +x package/{}/*'
      - run: ls package | xargs -I {} cp ${{ env.THIRD_PARTY_LICENSE_OUTPUT }} package/{}/
      - run: ls package | xargs -I {} cp README.md package/{}/
      - run: ls package | xargs -I {} cp README_ja.md package/{}/
      - run: ls package | xargs -I {} cp LICENSE package/{}/
      - run: ls . | xargs -I {} zip -r "{}.zip" "{}"
        working-directory: package
      - run: find package -type f | sort
      - run: |
          FILES=$(find package -type f | grep -F ".zip")
          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        id: release-files
      - uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3
        with:
          draft: true
          generate_release_notes: true
          files: package/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
